### ISSUE TITLE
Bugs with `template-string-converter.autoRemoveTemplateString`

### ISSUE THREAD

**Issue by karlhorky** [meganrogge/template-string-converter#43] opened 2021-04-02 10:55 UTC
First of all, thanks @meganrogge for your continued work on this extension, and @xNocken for creating the feature to convert back to a regular string when the interpolation markers (`${}`) are removed (in #19, original issue: #16).

The new feature is unfortunately somewhat buggy, making the editor actually frustratingly unusable in some cases.

Here are some buggy cases:

1. Adding a variable with an empty template string (for editing afterwards) causes it to be transformed to double quotes right away.

   ![Kapture 2021-04-02 at 12 40 30](https://user-images.githubusercontent.com/1935696/113409012-b24f4a00-93b0-11eb-8607-a2df472ba56a.gif)

   This particular issue above is avoided by only pressing the backtick key on the keyboard once, but this workaround doesn't work with tagged template literals:

   ![Kapture 2021-04-02 at 12 43 46](https://user-images.githubusercontent.com/1935696/113409207-170aa480-93b1-11eb-9784-6e4679d458ce.gif)

2. Removing the interpolation from a template string causes the cursor to jump to the end:

   ![Kapture 2021-04-02 at 12 52 29](https://user-images.githubusercontent.com/1935696/113409816-5dacce80-93b2-11eb-8977-78d813e96445.gif)

3. Typing inside an existing template string causes it to be converted to a string. This is exacerbated by **2** above.

   ![Kapture 2021-04-02 at 12 47 18](https://user-images.githubusercontent.com/1935696/113409467-9dbf8180-93b1-11eb-911f-ddcd3efac2dd.gif)

   This also is triggered by typing a `$` into an empty template string:

   ![Kapture 2021-04-02 at 12 50 57](https://user-images.githubusercontent.com/1935696/113409687-19213300-93b2-11eb-8a50-d367622243eb.gif)

I seem to have the feeling there were more problems with it, but I can't think of them right now. I'll follow up later with them if they come up.

It seems like some of these things may be solved by running this on file save. Hmmm... maybe also for the whole extension? @meganrogge what are your thoughts about running the transformations from this extension generally always on save? (eg. allowing configuration under `editor.codeActionsOnSave`?). This would also address cases like https://github.com/meganrogge/template-string-converter/issues/38 

Or, if not, then maybe making it so that these `autoRemoveTemplateString` transformations get applied on save.

**Comment by xNocken** [comment] 2021-04-02 13:31
I don't think that its a problem if it automatically removes the template strings on type. That's what the extension is for. If you have a normal string you can type normal strings with hardcoded content. If you then want to change it to a template string then just type ${ and its one. I already got used to using ' when writing template strings. 

Making it that its on save would make it more annoying to use. When you write ${} inside a normal string its basically a normal string. That means that you don't have autocomplete. And When removing it and waiting for safe could make it annoying because of linters. 

The bug I agree with that should be fixed is that it jumps after the string after changing it.

**Comment by karlhorky** [comment] 2021-04-02 14:46
> When you write ${} inside a normal string its basically a normal string. That means that you don't have autocomplete.

Good point, this is a downside of changing the whole extension to "transform on save". But it would still be valid for the `autoRemoveTemplateString` feature, which would not be affected by this.

> And When removing it and waiting for safe could make it annoying because of linters.

I think the downside of this is not as bad as the UX problems with all issues reported above.

**Comment by xNocken** [comment] 2021-04-02 18:30
I don't think that there is a good reason to change it. The extensions purpose is that you can easily write strings without thinking about what type of string you need. The way you use it is just wrong. Just use double or single quotes whenever you want to make a string. The extension switches it to template strings if you need it.

**Comment by meganrogge** [comment] 2021-05-24 19:19
I have removed the setting bc of complaints that it causes problems

**Comment by xNocken** [comment] 2021-05-24 19:48
But why remove it? The setting is off by default and if someone has problems with it they can turn it off. And imo this feature is equaly as important as the main feature. And all problems I've seen someone have with this is just that they want to write `` without the ${}. But that's where you need to disable it. That's why it's an option.

**Comment by meganrogge** [comment] 2021-05-24 21:04
https://github.com/meganrogge/template-string-converter/issues/47 seems pretty bad.

**Comment by xNocken** [comment] 2021-05-24 21:16
The problem there is that all changes done by the add on is tracked in the history. What happens if you revert that is that the add on changes it directly back to the normal string. That means that this should also occur in the other direction. A workaround for that would probably be to ignore changes done via the code history feature.

**Comment by meganrogge** [comment] 2021-05-24 21:18
If you submit a PR that fixes this, I'll merge it @xNocken

**Comment by karlhorky** [comment] 2021-05-25 08:00
Yeah, I think there are a number of pretty critical issues with this feature @xNocken. If you feel so strongly about it, why not invest some time in refactoring it to address these problems?

**Comment by xNocken** [comment] 2021-05-25 10:06
I fixed the biggest issue that the history gets overwritten and another issue you mentioned that the cursor jumps. I think that are all issues the option has. the other "issue" with writing `` without ${} is not a bug. If you want to write code like that disable that option.

**Comment by xNocken** [comment] 2021-05-25 10:17
Ok there is one thing i didnt realise where you are right. If you want to use them to make multli line strings. But thats fixed in my newest pr. It only converts them back if you delete something while it is singleline. And i dont know how i would fix that. From what i can see its not possible to see what exaclty was changed if you delete something. You only know where something got deleted.

**Comment by karlhorky** [comment] 2021-12-03 15:19
So just copying here from https://github.com/meganrogge/template-string-converter/pull/48#issuecomment-985570350 for visibility:

Ok, so it seems this feature is still somewhat buggy: 

It erroneously makes the following tagged template string into a double-quoted string, when hitting backspace anywhere inside the template string.

Notice there are no interpolations. It's important that it stay as a tagged template string.

```ts
export async function down(sql: Sql<{}>) {
  await sql`DROP TABLE reset_password_requests`;
}
```

---

I'm guessing the logic for this code for this feature is:

1. If the user is inside a template string AND hits backspace:
    1. switch to double quotes

This is maybe almost ok, but should probably do some better checks:

1. If the user is inside a template string AND there is an interpolation (`${` and `}` present in the string) AND there is NO interpolation AFTER hitting backspace:
    1. switch to double quotes

That seems like it would be a much more robust start of an implementation (probably also has weird edge cases, but at least it's much better than what's there now).

**Comment by meganrogge** [comment] 2021-12-03 15:20
I have found that the extension feels very buggy when that setting is enabled. @xNocken want to fix it as @karlhorky suggests?

**Comment by xNocken** [comment] 2021-12-03 15:52
His suggestions would require the extension to keep track of the amount of ${} in every string and every time something is changed it needs to check the strings if the amount changed and if it was something above 0 and now is 0 then remove it. I don't quite remember what info vscode gives you if you delete something. I guess you get the position where something was deleted right? This allows the extension to only check the amount changed of the current string. 

But the harder part would be to find the amount of ${} in every string, We would need to every time a file is opened search the whole file for template strings, count the amount of ${} and store it. But I don't think its as easy as it sounds. because if I remember correctly the current way of finding the template string is checking the current position and check for a ` before and after the cursor. If found that's the template string. 

I think to make this really reliable we would need to rewrite the extension and make the detection much better. We need to make the extension understand the code and the context the template string is used in. This would fix issues with template strings inside template strings or ` inside template strings.  It would maybe be easier if vscode would give you the chars that were deleted. But the last time I checked it only gave you an empty string to signal that something was deleted and not what.

I don't have the time or knowledge to do this. And I don't think we can do anything to fix this as long the code is just a big if else if.

**Comment by meganrogge** [comment] 2021-12-03 15:56
I might see if I have time over the holidays to look into this. I agree it might not be worth it to process the whole file (could be tons of lines), but that might be needed for it to be totally context aware.

**Comment by meganrogge** [comment] 2021-12-03 15:56
@karlhorky why do you keep this setting enabled if it bothers you so much?

**Comment by xNocken** [comment] 2021-12-03 16:39
And i dont see how you can have so many problems with it. I havnt had a single problem with it since i made the first version. Except maybe ` inside template strings and template strings inside template strings. And your current problem

```js
export async function down(sql: Sql<{}>) {
  await sql`DROP TABLE reset_password_requests`;
}
```

isnt this just the same as this?


```js
export async function down(sql: Sql<{}>) {
  await sql('DROP TABLE reset_password_requests');
}
```
The other problem you had that i fixed was you want to write a template string and type `` and it corrects it to "". Why dont just type "" and make the extension do its job when you type ${}. Or is this problem related to the thing above?

**Comment by karlhorky** [comment] 2021-12-03 17:29
> why do you keep this setting enabled if it bothers you so much?

Ah, because when it works, it's great! 👍 I think that it is the opposite feature of what this extension provides, and totally makes sense to have it!

**Comment by karlhorky** [comment] 2021-12-03 17:33
> isnt this just the same as this?

No, tagged template literals are different than calling a function.

> Why dont just type "" and make the extension do its job when you type ${}

Because tagged template literals (eg. with CSS) do not always have interpolation:

```js
const headerStyles = css`
  background-color: red;
`
```

---

The reason that I have so many different cases is because I'm teaching web development beginners at our bootcamp, and aside from the live coding that I do in lectures (where I find a lot of these problems, with basic things that beginners are learning), I often reproduce all the different things that they do with their code on my machine, and see errors.

**Comment by meganrogge** [comment] 2021-12-03 18:26
I appreciate that you point out these issues and wish I had more time to spend working on solutions to them. I imagine it would be a confusing experience for students who are just learning to see these unexpected cases. 😢

**Comment by xNocken** [comment] 2021-12-03 20:28
> @xNocken No, tagged template literals are different than calling a function.

@karlhorky 
This may not be the right place to ask this but what is the advantage over using this method? The arguments it gives you look pretty weird. The first argument is an array with all normal text and all other arguments are the values typed in ${}. 
I know this is very opinion based but couldn't you just call the function with func(['the text']) instead of func`the text`? For me it looks much cleaner and is easier to identify as a function call. And you maybe don't even want to put other text in another array. 
For example you call a function that takes an array and does cool stuff with all the lines in the array. And then you call the function like this and if you want to add a variable to a line it removes the variable and splits the line into two or am I missing something?
The only real usecase i can find for this is if you need the variables and text seperated to modify them or something. Like escape them for sql or make them a different color for a logger.

**Comment by karlhorky** [comment] 2021-12-04 10:50
> This may a bit off topic but what is the advantage over using this method?

Yeah, philosophical discussions about why to use tagged template literals are pretty off topic, I agree.

If you're interested in why the industry is using this technology, maybe take a look into common use cases such as Emotion, Postgres.js, etc. It's a very nice DX ("Developer Experience"), and integrates with many tools, such as [`vscode-styled-components`](https://github.com/styled-components/vscode-styled-components).

**Comment by karlhorky** [comment] 2021-12-04 10:53
> I appreciate that you point out these issues and wish I had more time to spend working on solutions to them. I imagine it would be a confusing experience for students who are just learning to see these unexpected cases. 😢

@meganrogge No worries, you're doing a great job! ❤️

For now I usually avoid recommending this particular `template-string-converter.autoRemoveTemplateString` option for students because it's still pretty buggy. But I would hope that in the future, it could be the default! 🙌

**Comment by meganrogge** [comment] 2021-12-06 15:53
I'll try to work on this over the holidays.

**Closed** 2021-12-28 04:14 UTC

**Comment by meganrogge** [comment] 2021-12-28 04:43
having trouble with vsce again, but will publish the extension with the above changes ASAP

**Comment by meganrogge** [comment] 2021-12-29 02:09
done

**Comment by meganrogge** [comment] 2021-12-29 02:11
here's what I did - only works for single line template strings at the moment, but won't have bugs for multi-line

if _within backticks and not within a template string_, AND _if previous version at the current cursor position used to be a template string_, then convert backticks to quotes

**Comment by karlhorky** [comment] 2021-12-29 15:49
This `template-string-converter.autoRemoveTemplateString` feature looks pretty good now, great work @meganrogge ! 🙌

**Comment by xNocken** [comment] 2022-01-12 10:14
Since i updated to the newer version (0.6.0) the extension is extremly buggy. It doesnt convert them back and sometimes doesnt even convert them to template strings. I havnt found a way to trigger the not converting to template string consistently but the not converting from bug is consistent.

And  @meganrogge did you forget to push the 0.6.0 changes? because the package json only says 0.5.9

**Comment by karlhorky** [comment] 2022-01-12 12:26
@xNocken can you come up with a reproducible example where the buggy behavior is triggered?

**Comment by meganrogge** [comment] 2022-01-12 13:06
The changes I made were unrelated to the code that converts to template string, so I find that surprising @xNocken. As @karlhorky said, pls give some examples of what causes the unexpected behavior.

**Comment by meganrogge** [comment] 2022-01-12 15:54
@xNocken I do see that sometimes the back-ticks aren't replaced with quotes. I will look into that. This solution is still a vast improvement because the problematic bugs @karlhorky reported related to the original version are now fixed.

**Comment by xNocken** [comment] 2022-01-12 18:32
i wrote a simple prototype that we could maybe use to detect the current line. Its a function that takes in a line and returns all lines where they start, end and what type they are. The code can probably be improved but this would allow us to accuratly say what string we are really in. i dont handle multiline template strings and there might be some other edge cases i dont handle so this would need a bit of testing.

https://gist.github.com/xNocken/4879d622f9f3044e7dad5557bf4c75a6

**Comment by xNocken** [comment] 2022-01-13 01:37
I updated it a bit since i posted it here to handle a few more edge cases. Should be easy to change it to take a cursor position and return the current string

**Comment by meganrogge** [comment] 2022-01-13 02:05
Please make a PR @xNocken and I'll test it. It should make use of the changes I made IE evaluating the previous document at the current position to see if it used to be a template string.

**Comment by xNocken** [comment] 2022-01-13 09:36
I dont have much time to create a pr and i think you would be able to do it much faster anyways because you know the code already.

**Comment by xNocken** [comment] 2022-01-14 07:59
I have an update for the not converting to template strings bug. Randomly when i type stuff and just write '' and inside it a ${ it does not convert them. Removing the ${ an rewriting it doesnt fix is and rewriting the whole string doesnt work either. But after some time the bug just disappears and it converty them when i type something in it.

**Comment by meganrogge** [comment] 2022-01-14 22:55
@xNocken can you pls clarify the repro steps?

**Comment by xNocken** [comment] 2022-01-15 01:22
## Expected behavior
it converts strings to template strings

## Actual behavior
it doesnt convert string to template strings

## How to reproduce
use the extension and be (un)lucky

## Attempts to fix it
- everything except restarting vscode

**Comment by karlhorky** [comment] 2022-01-15 07:44
@xNocken to create a good, reproducible example, it can help to start with code.

If you want to put effort into creating a new issue that will capture the problem so that the bug gets fixed, try this:

1. The next time that the buggy behavior happens for you, backtrack a bit (undo a few times until before the bug), and then perform the exact actions needed to make it happen again
2. Copy the code you think was causing it into a new file and try it again elsewhere, to verify that the bug is really associated with the code you suspect it is
3. If the buggy behavior didn't show up, you can instead copy more of your code again into a new file, and repeat until you find the correct code that causes the buggy behavior. Once you find the code and the set of actions that triggers the buggy behavior, then you can copy the code into a new issue in this repository, along with a detailed description of the actions that someone else would follow to trigger the buggy behavior. At this point, you could also consider taking a video to post along with the new issue (I recommend [Kap](https://getkap.co/) on macOS and [ScreenToGif](https://www.screentogif.com/) on Windows)

This is also what I went through to report the other issues in this repo.
